## å·¥ä½œæµçš„åç§°ï¼Œå¦‚æœçœç•¥ï¼Œåˆ™ä½¿ç”¨å½“å‰æ–‡ä»¶å
#name: Auto Deploy
#
## ä»å·¥ä½œæµç”Ÿæˆçš„å·¥ä½œæµè¿è¡Œçš„åç§°ï¼Œå¦‚æœçœç•¥ï¼Œåˆ™ä½¿ç”¨æäº¤æ—¶çš„commitä¿¡æ¯
#run-name: Deploy by @${{ github.actor }}
#
## è§¦å‘éƒ¨ç½²çš„æ¡ä»¶
#on:
#  # æ¯å½“ push åˆ° master åˆ†æ”¯æ—¶è§¦å‘éƒ¨ç½²
#  push:
#    branches:
#      - master
#
## å½“å‰æµç¨‹è¦æ‰§è¡Œçš„ä»»åŠ¡ï¼Œå¯ä»¥æ˜¯å¤šä¸ªã€‚[my_first_job]å°±æ˜¯ä¸€ä¸ªä»»åŠ¡
#jobs:
#  my_first_job:
#    # ä»»åŠ¡çš„åç§°ï¼Œä¸è®¾ç½®åˆ™é»˜è®¤my_first_job
#    name: build-and-deploy
#
#    # è¿è¡Œæ‰€éœ€è¦çš„è™šæ‹Ÿæœºç¯å¢ƒ
#    runs-on: windows-latest
#
#    # æ¯ä¸ªä»»åŠ¡ä¸‹çš„è¿è¡Œæ­¥éª¤ï¼ŒçŸ­æ¨ªæ  - è¡¨ç¤ºä¸€ä¸ªæ­¥éª¤ï¼Œä»ä¸Šè‡³ä¸‹ä¾æ¬¡æ‰§è¡Œã€‚
#    steps:
#      # clone è¯¥ä»“åº“çš„æºç åˆ°å·¥ä½œæµä¸­
#      - name: Clone Code
#        uses: actions/checkout@v3
#        with:
#          # "æœ€è¿‘æ›´æ–°æ—¶é—´"ç­‰ git æ—¥å¿—ç›¸å…³ä¿¡æ¯ï¼Œéœ€è¦æ‹‰å–å…¨éƒ¨æäº¤è®°å½•
#          fetch-depth: 0
#
#      # å®‰è£… Node ç¯å¢ƒ
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          # é€‰æ‹©è¦ä½¿ç”¨çš„ node ç‰ˆæœ¬
#          node-version: '20.12.0'
#
##      # å¦‚æœä½ çš„ä¾èµ–æ˜¯ä½¿ç”¨npmçš„ï¼Œç”¨è¿™ç§
##      # ç¼“å­˜ npm node_modules
##      - name: Cache dependencies
##        uses: actions/cache@v3
##        with:
##          path: ~/.npm
##          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
##          restore-keys: |
##            ${{ runner.os }}-npm-cache-
##
##      # å®‰è£…ä¾èµ– npm
##      - name: Install dependencies
##        # å¦‚æœæ²¡æœ‰å‘½ä¸­ç¼“å­˜æ‰æ‰§è¡Œ npm install
##        if: steps.cache-deps.outputs.cache-hit != 'true'
##        run: npm install
#
#      # å¦‚æœä½ çš„ä¾èµ–æ˜¯ä½¿ç”¨yarnçš„ï¼Œç”¨è¿™ç§
#      # ç¼“å­˜ yarn node_modules
#      - name: Cache dependencies
#        uses: actions/cache@v3
#        id: yarn-cache
#        with:
#          path: |
#            **/node_modules
#          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-yarn-
#
#      # å®‰è£…ä¾èµ– yarn
#      - name: Install dependencies
#        # å¦‚æœæ²¡æœ‰å‘½ä¸­ç¼“å­˜æ‰æ‰§è¡Œ npm install
#        if: steps.npm-cache.outputs.cache-hit != 'true'
#        run: yarn --frozen-lockfile
#
#      # è¿è¡Œæ„å»ºè„šæœ¬
#      - name: Run Build Script
#        run: npm run build
#
#      # éƒ¨ç½²åˆ° GitHub Pages
#      - name: Deploy to GitHub Pages
#        # æ­¤actionsçš„å®˜æ–¹æ–‡æ¡£ https://github.com/JamesIves/github-pages-deploy-action
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          # è¦éƒ¨ç½²çš„æ–‡ä»¶å¤¹ï¼Œå¿…å¡«
#          FOLDER: docs/.vuepress/dist
#          # å¸Œæœ›éƒ¨ç½²çš„åˆ†æ”¯ï¼Œé»˜è®¤gh-pages
#          BRANCH: master
#          # # ä»“åº“èŒƒå›´çš„è®¿é—®ä»¤ç‰Œï¼Œå¯ä»¥å°†ä¸ªäººä»¤ç‰Œçš„å€¼å­˜å‚¨åœ¨GitHub Secretsä¸­
#          # # é»˜è®¤æƒ…å†µæ˜¯ä¸éœ€è¦å¡«çš„ï¼Œå¦‚æœæ‚¨éœ€è¦æ›´å¤šæƒé™ï¼Œä¾‹å¦‚éƒ¨ç½²åˆ°å¦ä¸€ä¸ªå­˜å‚¨åº“æ‰éœ€è¦å¡«å†™
#          # # ACCESS_TOKEN å¯¹åº”GitHub Secretsä¸­è®¾ç½®çš„å­—æ®µï¼Œä¸è¦ç…§æ¬
#          # TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          # # éƒ¨ç½²åˆ°GitHubçš„ä¸åŒä»“åº“ <ç”¨æˆ·å>/<ä»“åº“å>
#          # # æ­¤é€‰é¡¹å¿…é¡»é…ç½®äº†TOKENæ‰èƒ½æ­£å¸¸æ‰§è¡Œ
#          # REPOSITORY-NAME: leoleor/leo2
# the former is for ubuntu plantform

name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest # The first job utilizes windows-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn build

      - name: Upload Artifacts ğŸ”º # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: build

  deploy:
    concurrency: ci-${{ github.ref }}
    needs: [build] # The second job must depend on the first one to complete before running and uses ubuntu-latest instead of windows.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Download Artifacts ğŸ”» # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'site' # The deployment folder should match the name of the artifact. Even though our project builds into the 'build' folder the artifact name of 'site' must be placed here.
